[book]
authors = ["Steve Klabnik"]
language = "en"
multilingual = false
src = "src"
title = "Steve's Jujutsu Tutorial"

[output.html]
git-repository-url = "https://github.com/steveklabnik/jujutsu-tutorial"
